# Generated by Django 4.1.4 on 2022-12-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='watchmode_id',
            field=models.IntegerField(null=True),
        ),
    ]
