# Generated by Django 4.1.4 on 2022-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0003_alter_person_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
