# Generated by Django 4.1.4 on 2022-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0004_alter_film_imdb_id_alter_film_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
