# Generated by Django 4.1.4 on 2022-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0005_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
