# Generated by Django 4.1.4 on 2022-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0006_alter_film_title_alter_film_tmdb_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=25, null=True)),
                ('tmdb_id', models.IntegerField(null=True)),
                ('tmdb_type', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email addresss'),
        ),
    ]
