# Generated by Django 4.1.4 on 2022-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watch', '0007_popularmovies_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepersons',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='favoritepersons',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PopularMovies',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='film_id',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='film_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='favoritefilms',
            name='film_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='FavoritePersons',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
